services:
  streamlitapp:
    #image: streamlit-home:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:8051
    command: [
      "streamlit", "run",
      "home_dashboard.py",
      "--server.port", "8051",
      "--server.address", "0.0.0.0"
    ]
